# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fused',
            field=models.BooleanField(default=False),
        ),
    ]
