# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_fused'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fused_into',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='finance.Transaction'),
        ),
    ]
