# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_fused_into'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fused_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.Transaction'),
        ),
    ]
