# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20160129_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fusion',
            field=models.BooleanField(default=False),
        ),
    ]
